# Ping Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
spec:
  replicas: 3  # Default number of replicas
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
        - name: ping-container
          #image: ping-service:latest  # Replace with your image name if pulling from a registry
          image: arxemond777/ping-service:latest  # Replace with your image name if pulling from a registry
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"  # Maximum memory the container can use
              cpu: "1"         # Maximum CPU the container can use
            requests:
              memory: "256Mi"  # Amount of memory the container is guaranteed
              cpu: "0.5"       # Amount of CPU the container is guaranteed
          # Optional: Add environment variables, volumes, etc.
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          #restartPolicy: Always

---
# Horizontal Pod Autoscaler definition
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-deployment
  minReplicas: 3  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Scale up if CPU usage exceeds 80%