apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          #image: pong-service  # Replace with your Minikube Docker image name
          image: arxemond777/pong-service:latest  # Replace with your image name if pulling from a registry
          ports:
            - containerPort: 5001
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          #restartPolicy: Always
