apiVersion: v1
kind: Service
metadata:
  name: pong-service
spec:
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 5001       # Порт, через который сервис будет доступен внутри кластера
      targetPort: 5001  # Порт контейнера, на котором приложение слушает
      nodePort: 30001   # Порт, который будет открыт на всех нодах кластера для внешнего доступа
  type: NodePort       # Это делает сервис доступным из внешнего мира через NodePort